# Generated by Django 5.2.8 on 2025-11-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="descriptiom",
            new_name="description",
        ),
    ]
